"""
UI Styling and Theme Components
"""

from typing import Optional

import streamlit as st

from src.ui.themes.theme import theme

# ==================== COLOR SYSTEM ====================
# Import colors from unified theme but keep for backward compatibility


class NeutralColors:
    """Backward-compat passthrough — every attribute now aliases the
    canonical ``theme.colors`` tokens so this class can no longer drift
    from the rest of the app. New code should import ``theme`` directly
    from ``src.ui.themes.theme`` and use ``theme.colors.*``.
    """

    # Primary brand colors
    PRIMARY = theme.colors.primary
    PRIMARY_HOVER = theme.colors.primary_hover
    PRIMARY_LIGHT = theme.colors.primary_bg

    # Semantic colors
    SUCCESS = theme.colors.success
    SUCCESS_LIGHT = theme.colors.success_bg
    WARNING = theme.colors.warning
    WARNING_LIGHT = theme.colors.warning_bg
    DANGER = theme.colors.danger
    DANGER_LIGHT = theme.colors.danger_bg
    INFO = theme.colors.info
    INFO_LIGHT = theme.colors.info_bg

    # Neutral grays
    NEUTRAL_900 = theme.colors.neutral_900
    NEUTRAL_800 = theme.colors.neutral_800
    NEUTRAL_700 = theme.colors.neutral_700
    NEUTRAL_600 = theme.colors.neutral_600
    NEUTRAL_500 = theme.colors.neutral_500
    NEUTRAL_400 = theme.colors.neutral_400
    NEUTRAL_300 = theme.colors.neutral_300
    NEUTRAL_200 = theme.colors.neutral_200
    NEUTRAL_100 = theme.colors.neutral_100
    NEUTRAL_50 = theme.colors.neutral_50

    # Adaptive overlays — kept independent of theme.colors because they
    # are currentColor-relative, not palette-derived.
    BORDER_COLOR = theme.colors.border
    SHADOW_COLOR = "rgba(0, 0, 0, 0.1)"
    OVERLAY_COLOR = "rgba(0, 0, 0, 0.05)"

    # Chart colors — Wong colorblind-safe palette from theme.
    CHART_COLORS = theme.colors.chart_colors_categorical


# ==================== CSS STYLES ====================


def get_neutral_css() -> str:
    """
    Generate CSS that works well in both light and dark modes.
    Uses relative colors and careful contrast ratios.
    """
    return f"""
    <style>
    /* =====================================================================
       STREAMLIT INTERNAL SELECTORS THIS BUNDLE DEPENDS ON
       These targets are NOT public API. They are auto-generated or
       semi-stable attributes that may change across Streamlit versions.
       Revalidate after every Streamlit upgrade.

         section[data-testid="stSidebar"]           — sidebar root (stable ≥1.30)
         [data-testid="stMetric"] / metric-container — st.metric wrappers
         [data-testid="stMetricValue"]              — metric number
         [data-testid="stMetricDelta"]              — metric delta
         [data-testid="metric-value"]               — alternate (older builds)
         [data-testid="stForm"] / stFormSubmitButton — st.form internals
         [data-testid="stDateInput"]                — date picker
         [data-testid="stCheckbox"]                 — checkbox
         [data-testid="stNotification"]             — toast/notification
         [data-testid="stExpander"]                 — expander panels
         [data-testid="stVerticalBlock"]            — generic block wrapper
         .stTabs [data-baseweb="tab-list"]          — tab strip (BaseWeb)
         .stTabs [data-baseweb="tab"]               — individual tab
         .stTabs [data-baseweb="tab-panel"]         — active panel
         .stMultiSelect [data-baseweb="tag"]        — multiselect pill
         .stSelectbox [data-baseweb="select"]       — selectbox shell
         .stButton > button                         — button element
         .stDataFrame                               — Arrow dataframe wrapper
         .streamlit-expanderHeader                  — legacy expander header
         .main > .block-container                   — main content container

       The previously-targeted ``.css-1d391kg`` (autogenerated sidebar
       class) was removed — secondaryBackgroundColor in config.toml drives
       the sidebar now.
       ===================================================================== */

    /* =====================================================================
       DESIGN TOKENS — single source of truth, all bound to theme.* in
       src/ui/themes/theme.py. Token taxonomy mirrors a DASH-style editorial
       dashboard system applied to this app's existing palette. Legacy var
       names (--text-color, --background-color, --border-color, etc.) are
       defined as aliases so existing inline-style consumers (trends.py,
       filters.py) continue to resolve.
       ===================================================================== */
    :root {{
        /* Brand */
        --brand-deep:  {theme.colors.primary};
        --brand-mid:   {theme.colors.primary_hover};
        --brand-dark:  {theme.colors.primary_dark};
        --brand-light: {theme.colors.primary_light};
        --brand-bg:    {theme.colors.primary_bg};

        /* Surfaces */
        --bg-page:     {theme.colors.background_secondary};
        --bg-card:     {theme.colors.background};
        --bg-card-alt: {theme.colors.surface};
        --bg-hover:    {theme.colors.surface_hover};
        --bg-active:   {theme.colors.surface_hover};

        /* Borders */
        --border:       {theme.colors.border};
        --border-light: {theme.colors.border_light};
        --border-dark:  {theme.colors.border_dark};

        /* Text */
        --text-primary:   {theme.colors.text_primary};
        --text-secondary: {theme.colors.text_secondary};
        --text-muted:     {theme.colors.text_muted};

        /* Status (DASH "rate" semantics mapped to our semantic colors) */
        --good:        {theme.colors.success};
        --good-bg:     {theme.colors.success_bg};
        --bad:         {theme.colors.danger};
        --bad-bg:      {theme.colors.danger_bg};
        --warn:        {theme.colors.warning};
        --warn-bg:     {theme.colors.warning_bg};
        --info-color:  {theme.colors.info};
        --info-bg:     {theme.colors.info_bg};
        --neutral:     {theme.colors.neutral_500};
        --neutral-bg:  {theme.colors.neutral_100};

        /* Spacing (4px scale) */
        --sp-1: {theme.spacing.xs};      /* 0.25rem */
        --sp-2: {theme.spacing.sm};      /* 0.5rem  */
        --sp-3: 0.75rem;
        --sp-4: {theme.spacing.md};      /* 1rem    */
        --sp-5: 1.25rem;
        --sp-6: {theme.spacing.lg};      /* 1.5rem  */
        --sp-7: {theme.spacing.xl};      /* 2rem    */
        --sp-8: 2.5rem;
        --sp-9: {theme.spacing.xxl};     /* 3rem    */
        --sp-10: {theme.spacing.xxxl};   /* 4rem    */

        /* Radii */
        --r-xs:   {theme.borders.radius_sm};   /* 0.25rem */
        --r-sm:   {theme.borders.radius_md};   /* 0.5rem  */
        --r:      {theme.borders.radius_md};   /* default 0.5rem */
        --r-lg:   {theme.borders.radius_lg};   /* 0.75rem */
        --r-xl:   {theme.borders.radius_xl};   /* 1rem    */
        --r-full: {theme.borders.radius_full}; /* 9999px  */

        /* Shadows */
        --shadow-xs:    {theme.shadows.sm};
        --shadow-sm:    {theme.shadows.card};
        --shadow-md:    {theme.shadows.md};
        --shadow-lg:    {theme.shadows.lg};
        --shadow-hover: {theme.shadows.hover};

        /* Font stacks */
        --font-sans: {theme.typography.font_family};
        --font-mono: {theme.typography.font_mono};

        /* Page padding token — paired with the tab-strip full-bleed
           negative-margin hack so the two values can't drift apart.
           If you change the value here, both `.main > .block-container`
           padding and `.stTabs [data-baseweb="tab-list"]` negative
           margin update together. */
        --block-pad: 5rem;

        /* ----- Legacy aliases (do not remove until callers migrate) ----- */
        --text-color:                  var(--text-primary);
        --text-color-secondary:        var(--text-secondary);
        --background-color:            var(--bg-card);
        --secondary-background-color:  var(--bg-page);
        --border-color:                var(--border);
        --border-radius:               var(--r);
        --border-radius-sm:            var(--r-xs);
        --border-radius-lg:            var(--r-lg);
        --spacing-xs:                  var(--sp-1);
        --spacing-sm:                  var(--sp-2);
        --spacing-md:                  var(--sp-4);
        --spacing-lg:                  var(--sp-6);
        --spacing-xl:                  var(--sp-7);
    }}

    /* ===== Global Resets ===== */
    * {{
        box-sizing: border-box;
    }}

    /* ===== Typography =====
       NOTE: font-family / heading sizes / heading weights / line height are
       set by Streamlit's native [theme] block in .streamlit/config.toml
       (font, headingFontSizes, headingFontWeights, baseFontWeight). The
       only thing left here is anti-aliasing — Streamlit doesn't expose it. */
    html, body {{
        -webkit-font-smoothing: antialiased;
        -moz-osx-font-smoothing: grayscale;
    }}

    h1, h2, h3, h4, h5, h6 {{
        margin-bottom: var(--spacing-md);
        color: var(--text-primary);
    }}

    /* ===== Container Styling ===== */
    .block-container {{
        padding: var(--spacing-lg) var(--spacing-xl) !important;
        max-width: 100%;
    }}

    /* ===== Card Components ===== */
    .neutral-card {{
        background: var(--bg-card);
        border: 1px solid var(--border-color);
        border-radius: var(--border-radius);
        padding: var(--spacing-lg);
        margin-bottom: var(--spacing-md);
        transition: all 0.2s ease;
    }}

    .neutral-card:hover {{
        background: var(--bg-hover);
        box-shadow: var(--shadow-md);
    }}

    /* ===== Metric Cards ===== */
    div[data-testid="stMetric"],
    div[data-testid="metric-container"] {{
        background: var(--bg-card);
        border: 1px solid var(--border-color);
        border-radius: var(--border-radius);
        padding: var(--spacing-lg);
        transition: all 0.2s ease;
        position: relative;
        overflow: visible;
        min-height: 80px;
    }}

    /* Metric label styling */
    div[data-testid="stMetric"] label {{
        font-size: 0.875rem !important;
        color: var(--text-secondary) !important;
        white-space: normal !important;
        word-wrap: break-word !important;
        margin-bottom: 0.25rem !important;
    }}

    /* Metric value styling */
    div[data-testid="stMetric"] div[data-testid="stMetricValue"] {{
        font-size: 1.5rem !important;
        font-weight: 600 !important;
        color: var(--text-primary) !important;
        white-space: normal !important;
        word-wrap: break-word !important;
        line-height: 1.2 !important;
    }}

    /* Metric delta styling */
    div[data-testid="stMetric"] div[data-testid="stMetricDelta"] {{
        font-size: 0.875rem !important;
        margin-top: 0.25rem !important;
        white-space: normal !important;
        word-wrap: break-word !important;
    }}

    /* Metric card accent border */
    div[data-testid="stMetric"]::before,
    div[data-testid="metric-container"]::before {{
        content: '';
        position: absolute;
        left: 0;
        top: 0;
        bottom: 0;
        width: 4px;
        background: {NeutralColors.PRIMARY};
    }}

    /* ===== Buttons ===== */
    .stButton > button {{
        background: {NeutralColors.PRIMARY};
        color: white;
        border: none;
        border-radius: var(--border-radius-sm);
        padding: var(--spacing-sm) var(--spacing-lg);
        font-weight: 500;
        transition: all 0.2s ease;
        cursor: pointer;
    }}

    .stButton > button:hover {{
        background: {NeutralColors.PRIMARY_HOVER};
        transform: translateY(-1px);
        box-shadow: var(--shadow-md);
    }}

    .stButton > button:active {{
        transform: translateY(0);
    }}

    /* Secondary button style */
    .stButton.secondary > button {{
        background: transparent;
        color: {NeutralColors.PRIMARY};
        border: 1px solid {NeutralColors.PRIMARY};
    }}

    .stButton.secondary > button:hover {{
        background: {NeutralColors.PRIMARY_LIGHT};
    }}

    /* ===== Expanders ===== */
    .streamlit-expanderHeader {{
        background: var(--bg-card);
        border: 1px solid var(--border-color);
        border-radius: var(--border-radius-sm);
        font-weight: 500;
        color: var(--text-primary);
        transition: all 0.2s ease;
    }}

    .streamlit-expanderHeader:hover {{
        background: var(--bg-hover);
    }}

    /* ===== DataFrames ===== */
    .dataframe {{
        border: 1px solid var(--border-color);
        border-radius: var(--border-radius);
        overflow: hidden;
    }}

    .dataframe thead th {{
        background: var(--bg-hover);
        color: var(--text-primary);
        font-weight: 600;
        padding: var(--spacing-sm) var(--spacing-md);
        border-bottom: 2px solid var(--border-color);
    }}

    .dataframe tbody tr {{
        transition: background 0.2s ease;
    }}

    .dataframe tbody tr:hover {{
        background: var(--bg-hover);
    }}

    .dataframe tbody td {{
        padding: var(--spacing-sm) var(--spacing-md);
        border-bottom: 1px solid var(--border-color);
    }}

    /* ===== Tabs ===== */
    .stTabs [data-baseweb="tab-list"] {{
        gap: var(--spacing-xs);
        background: var(--bg-card);
        padding: var(--spacing-xs);
        border-radius: var(--border-radius);
        border: 1px solid var(--border-color);
    }}

    .stTabs [data-baseweb="tab"] {{
        background: transparent;
        border: none;
        color: var(--text-secondary);
        font-weight: 500;
        padding: var(--spacing-sm) var(--spacing-lg);
        border-radius: var(--border-radius-sm);
        transition: all 0.2s ease;
    }}

    .stTabs [data-baseweb="tab"]:hover {{
        background: var(--bg-hover);
        color: var(--text-primary);
    }}

    .stTabs [aria-selected="true"] {{
        background: {NeutralColors.PRIMARY} !important;
        color: white !important;
    }}

    /* ===== Alerts & Info boxes ===== */
    .stAlert {{
        background: var(--bg-card);
        border: 1px solid var(--border-color);
        border-radius: var(--border-radius);
        padding: var(--spacing-md);
    }}

    /* ===== Dividers ===== */
    hr {{
        border: none;
        border-top: 1px solid var(--border-color);
        margin: var(--spacing-xl) 0;
    }}

    /* Custom styled divider */
    .styled-divider {{
        height: 2px;
        background: linear-gradient(
            to right,
            transparent,
            {NeutralColors.PRIMARY},
            transparent
        );
        border: none;
        margin: var(--spacing-xl) 0;
    }}

    /* ===== Sidebar =====
       Background is driven by [theme] secondaryBackgroundColor in
       .streamlit/config.toml. The legacy .css-1d391kg selector (autogenerated
       and brittle across Streamlit versions) has been removed. If sidebar-
       specific overrides are ever needed, target section[data-testid="stSidebar"]
       which has been stable since Streamlit 1.30+. */

    /* ===== Tooltips ===== */
    .tooltip {{
        background: {NeutralColors.NEUTRAL_900};
        color: white;
        padding: var(--spacing-sm);
        border-radius: var(--border-radius-sm);
        font-size: 0.875rem;
        box-shadow: var(--shadow-lg);
    }}

    /* ===== Loading states ===== */
    .stSpinner > div {{
        border-color: {NeutralColors.PRIMARY} transparent transparent transparent;
    }}

    /* ===== Accessibility improvements ===== */
    :focus {{
        outline: 2px solid {NeutralColors.PRIMARY};
        outline-offset: 2px;
    }}

    /* Remove default focus for better custom styling */
    *:focus:not(:focus-visible) {{
        outline: none;
    }}

    /* =====================================================================
       DASH-STYLE COMPONENT CSS
       Editorial dashboard primitives: panels, KPI cards, rate pills,
       three-things callout, sticky table headers. All tokens come from
       :root above so the palette stays unified.
       ===================================================================== */

    .panel {{
        background: var(--bg-card);
        border: 1px solid var(--border-light);
        border-radius: var(--r);
        padding: var(--sp-5);
        box-shadow: var(--shadow-sm);
        transition: box-shadow .18s cubic-bezier(.165, .84, .44, 1);
    }}
    .panel:hover {{box-shadow: var(--shadow-md); }}
    .panel--lede {{padding: var(--sp-7); }}
    .panel--lede > h2:first-child {{
        font-size: clamp(1.5rem, 1.25rem + 1vw, 2rem);
        margin: 0 0 var(--sp-4);
        color: var(--text-primary);
    }}

    .kpi-card {{
        background: var(--bg-card);
        border: 1px solid var(--border-light);
        border-left: 4px solid var(--brand-deep);
        border-radius: var(--r);
        padding: var(--sp-5);
        text-align: center;
        box-shadow: var(--shadow-sm);
    }}
    .kpi-card .eyebrow {{margin-bottom: var(--sp-2); }}
    .kpi-card .num     {{font-size: 1.75rem; font-weight: 700; color: var(--text-primary); }}
    .kpi-card--hero {{
        text-align: left;
        background: linear-gradient(135deg, var(--bg-card) 0%, var(--bg-page) 100%);
        display: grid;
        grid-template-areas: "label" "value" "yoy";
        gap: var(--sp-2);
        padding: var(--sp-6);
    }}
    .kpi-card--hero .eyebrow  {{grid-area: label; }}
    .kpi-card--hero .hero-kpi {{grid-area: value; }}
    .kpi-card--hero .yoy      {{grid-area: yoy; }}

    .pill {{
        display: inline-block;
        padding: 2px 10px;
        border-radius: var(--r-full);
        font-size: 0.75rem;
        font-weight: 600;
        font-variant-numeric: tabular-nums;
        line-height: 1.5;
    }}
    .pill--good {{background: var(--good-bg);    color: var(--good); }}
    .pill--bad  {{background: var(--bad-bg);     color: var(--bad); }}
    .pill--mid  {{background: var(--neutral-bg); color: var(--neutral); }}
    .pill--warn {{background: var(--warn-bg);    color: var(--warn); }}
    .pill--info {{background: var(--info-bg);    color: var(--info-color); }}

    .three-things {{
        display: grid;
        grid-template-columns: repeat(3, 1fr);
        gap: var(--sp-5);
        margin: var(--sp-6) 0;
    }}
    .three-things__icon {{
        width: 2.5rem; height: 2.5rem;
        border-radius: var(--r-full);
        display: inline-flex; align-items: center; justify-content: center;
        margin-bottom: var(--sp-3);
        font-size: 1.25rem;
    }}
    .three-things__icon--good {{background: var(--good-bg);    color: var(--good); }}
    .three-things__icon--bad  {{background: var(--bad-bg);     color: var(--bad); }}
    .three-things__icon--mid  {{background: var(--neutral-bg); color: var(--neutral); }}
    @media (max-width: 768px) {{
        .three-things {{grid-template-columns: 1fr; }}
    }}

    /* Sticky table headers for wrapped st.dataframe widgets — keeps the
       header visible when long tables are scrolled inside their container. */
    .stDataFrame thead th {{
        position: sticky; top: 0; z-index: 1;
        background: var(--bg-card-alt);
    }}

    /* ===== Utility classes ===== */
    .text-muted {{color: var(--text-muted); }}
    .text-small {{font-size: 0.875rem; }}
    .text-large {{font-size: 1.125rem; }}
    .font-mono {{font-family: var(--font-mono); }}

    .mt-1 {{margin-top: var(--sp-2); }}
    .mt-2 {{margin-top: var(--sp-4); }}
    .mt-3 {{margin-top: var(--sp-6); }}

    .mb-1 {{margin-bottom: var(--sp-2); }}
    .mb-2 {{margin-bottom: var(--sp-4); }}
    .mb-3 {{margin-bottom: var(--sp-6); }}

    /* ===== DASH-style typography utilities ===== */
    /* Tabular figures for any numeric content (KPIs, table cells, metric
       values). Digits occupy equal width so columns of numbers align. */
    .num {{font-variant-numeric: tabular-nums; }}

    /* Auto-apply to Streamlit metric values and dataframe cells so we
       don't have to add the class at every call site. */
    [data-testid="stMetricValue"],
    [data-testid="metric-value"],
    .stDataFrame td,
    .stDataFrame th {{
        font-variant-numeric: tabular-nums;
    }}

    /* Uppercase "eyebrow" label used above KPIs, filter groups, and section
       starts. Smaller, muted, letter-spaced. */
    .eyebrow {{
        text-transform: uppercase;
        letter-spacing: 0.05em;
        font-weight: 600;
        color: var(--text-muted);
        font-size: 0.6875rem;
        line-height: 1.5;
    }}

    /* Editorial hero KPI number for the largest single-figure cards. */
    .hero-kpi {{
        font-family: var(--font-mono);
        font-weight: 800;
        font-size: clamp(2.25rem, 1.5rem + 3vw, 3rem);
        letter-spacing: -0.025em;
        font-variant-numeric: tabular-nums;
        color: var(--text-primary);
        line-height: 1.1;
    }}

    /* Lede paragraph — chapter-headlining narrative text capped to
       comfortable measure. */
    .lede {{
        font-size: 1.125rem;
        line-height: 1.7;
        color: var(--text-secondary);
        max-width: 75ch;
    }}
    .lede strong {{color: var(--text-primary); font-weight: 600; }}
    .lede em      {{color: var(--brand-deep); font-style: normal; font-weight: 500; }}

    /* Opt-in fluid heading classes — use these instead of native h1-h6 when
       a heading should scale with viewport. Streamlit's native
       headingFontSizes drives bare <h1>..<h6>; these overrides apply only
       when the class is explicitly set. */
    .heading-fluid-1 {{font-size: clamp(1.75rem, 1.4rem + 1.5vw, 2.5rem); }}
    .heading-fluid-2 {{font-size: clamp(1.5rem, 1.25rem + 1vw, 2rem); }}
    .heading-fluid-3 {{font-size: clamp(1.25rem, 1.1rem + 0.6vw, 1.5rem); }}

    /* ===== Responsive adjustments ===== */
    @media (max-width: 768px) {{
        .block-container {{
            padding: var(--spacing-md) !important
        }}

        h1 {{font-size: 1.5rem
            }}
        h2 {{font-size: 1.25rem
            }}
        h3 {{font-size: 1.125rem
            }}
    }}

    /* ===== Fix for metric cards in columns ===== */
    .stColumn > div > div > div[data-testid="stVerticalBlock"] > div[data-testid="stMetric"] {{
        width: 100% !important;
        box-sizing: border-box !important;
    }}

    /* Ensure columns don't overflow */
    .stColumn {{
        min-width: 0 !important;
        flex: 1 1 0 !important;
    }}

    /* Fix metric container spacing */
    div[data-testid="stMetric"] {{
        margin-bottom: 0.5rem !important;
    }}

    /* Prevent text overflow in metric cards */
    div[data-testid="stMetric"] * {{
        max-width: 100% !important;
        overflow-wrap: break-word !important;
    }}

    /* ====================================================================
       Centralized rules (Phase 1, see UI_LAYOUT_AUDIT.md)
       Three CSS sources were merged here so the whole app loads one block:
         - main.inject_custom_css        (was global)
         - components.apply_metric_card_style  (was per-call on dashboard)
         - dashboard.apply_neutral_tab_style   (was dashboard-only)
       Cascade order is intentional: rules later in the file override
       earlier rules of equal specificity.
       ==================================================================== */

    /* ===== From main.inject_custom_css ===== */
    /* Soften Streamlit multiselect/filter pills */
    .stMultiSelect [data-baseweb="tag"] {{
        background-color: {theme.colors.primary_bg_subtle} !important;
        border: 1px solid {theme.colors.border} !important;
        color: {theme.colors.text_primary} !important;
    }}

    /* Native dataframe wrapper styling (applied alongside the .dataframe
       rules above; .stDataFrame is the Streamlit wrapper, .dataframe is
       the inner pandas-emitted table). */
    .stDataFrame {{
        border: 1px solid {theme.colors.border} !important;
        border-radius: {theme.borders.radius_md} !important;
    }}

    /* Header background is now driven by [theme] dataframeHeaderBackgroundColor
       in config.toml. We keep the typography and border tweaks here. */
    .stDataFrame th {{
        color: {theme.colors.text_primary} !important;
        font-weight: 600 !important;
        padding: 12px !important;
        border-bottom: 2px solid {theme.colors.border} !important;
    }}

    .stDataFrame td {{
        padding: 10px 12px !important;
        border-bottom: 1px solid {theme.colors.border_light} !important;
    }}

    .stDataFrame tr:hover {{
        background-color: {theme.colors.surface_hover} !important;
    }}

    /* Soften alert boxes. border-radius is now native (baseRadius). */
    .stAlert {{
        padding: 1rem !important;
    }}

    /* Button overrides — border-radius is now native (baseRadius).
       The .stButton block above is the structural baseline. */
    .stButton > button {{
        font-weight: 500 !important;
        transition: all 0.2s ease !important;
    }}

    .stButton > button:hover {{
        transform: translateY(-1px) !important;
        box-shadow: {theme.shadows.md} !important;
    }}

    /* Expander header — border-radius is now native (baseRadius). */
    .streamlit-expanderHeader {{
        background-color: {theme.colors.background_secondary} !important;
        font-weight: 600 !important;
    }}

    /* Selectbox border-radius is now native (baseRadius). */

    /* Notification visual weight. */
    [data-testid="stNotification"] {{
        background-color: {theme.colors.info_bg_subtle} !important;
        border-left: 3px solid {theme.colors.info} !important;
    }}

    /* ===== Metric cards (was components.apply_metric_card_style) =====
       These rules previously injected only on dashboard sections that
       called ui.apply_metric_card_style(). Now applied globally so every
       st.metric in the app gets the same enhanced treatment. */
    div[data-testid="metric-container"] {{
        background: linear-gradient(135deg, rgba(255,255,255,0.9) 0%, rgba(248,250,252,0.9) 100%);
        border: 1px solid {theme.colors.border};
        border-left: 4px solid {theme.colors.primary};
        border-radius: {theme.borders.radius_lg};
        padding: 1.25rem;
        margin: 0.5rem 0;
        box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08), 0 1px 3px rgba(0, 0, 0, 0.05);
        transition: all 0.3s ease;
        min-height: auto !important;
        height: auto !important;
        overflow: visible !important;
    }}

    div[data-testid="metric-container"]:hover {{
        transform: translateY(-2px);
        box-shadow: 0 4px 12px rgba(0, 0, 0, 0.12);
    }}

    div[data-testid="metric-container"] label {{
        color: {theme.colors.text_muted};
        font-size: {theme.typography.size_sm};
        font-weight: {theme.typography.weight_medium};
        text-transform: uppercase;
        letter-spacing: 0.05em;
        white-space: normal !important;
        word-wrap: break-word !important;
        line-height: 1.4;
    }}

    div[data-testid="metric-container"] [data-testid="metric-value"] {{
        color: {theme.colors.text_primary};
        font-weight: {theme.typography.weight_bold};
        font-size: clamp(1.25rem, 2vw, {theme.typography.size_2xl});
        white-space: normal !important;
        word-wrap: break-word !important;
        overflow-wrap: break-word !important;
        line-height: 1.2;
    }}

    div[data-testid="metric-container"] [data-testid="metric-delta"] {{
        font-size: {theme.typography.size_sm};
        font-weight: {theme.typography.weight_medium};
        white-space: normal !important;
        word-wrap: break-word !important;
    }}

    /* Equal-height metric containers in column layouts. */
    div[data-testid="column"] > div > div[data-testid="metric-container"] {{
        height: 100%;
        display: flex;
        flex-direction: column;
        justify-content: space-between;
    }}

    /* ===== Tab strip (was dashboard.apply_neutral_tab_style) =====
       NOTE: full-bleed hack ahead. The .stTabs [data-baseweb="tab-list"]
       block bleeds past the page padding using a negative margin that
       must equal the page's left/right padding. To avoid the two values
       drifting, both now reference `var(--block-pad)` (defined in :root).
       The hack is still fragile against Streamlit DOM-structure changes —
       revalidate visually on every Streamlit upgrade. */
    .stTabs {{
        width: 100% !important;
        font-family: var(--font-sans);
    }}

    .stTabs [data-baseweb="tab-list"] {{
        gap: 0.75rem;
        background-color: transparent;
        border-radius: 0;
        border: none;
        margin: 0 calc(-1 * var(--block-pad));
        padding: 1rem var(--block-pad);
        margin-bottom: 2rem;
        background: var(--bg-page);
        border-top: 1px solid var(--border);
        border-bottom: 1px solid var(--border);
        display: flex;
        justify-content: center;
    }}

    .stTabs [data-baseweb="tab"] {{
        height: 52px;
        padding: 0 40px;
        background-color: rgba(255, 255, 255, 0.9);
        border: 1px solid rgba(0, 0, 0, 0.08);
        border-radius: 8px;
        color: rgba(0, 0, 0, 0.85);
        font-weight: 500;
        font-size: 1rem;
        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
        transition: all 0.2s ease;
        white-space: nowrap;
        position: relative;
        flex: 1 1 auto;
        min-width: 140px;
        max-width: 220px;
        box-shadow: 0 1px 3px rgba(0, 0, 0, 0.05);
        margin: 0 6px;
    }}

    .stTabs [data-baseweb="tab"]:hover {{
        background-color: rgba(255, 255, 255, 1);
        border-color: rgba(0, 0, 0, 0.15);
        color: rgba(0, 0, 0, 0.95);
        transform: translateY(-1px);
        box-shadow: 0 2px 6px rgba(0, 0, 0, 0.1);
    }}

    .stTabs [aria-selected="true"] {{
        background-color: {NeutralColors.PRIMARY} !important;
        color: white !important;
        font-weight: 600;
        border-color: {NeutralColors.PRIMARY} !important;
        box-shadow: 0 2px 8px rgba(33, 150, 243, 0.3) !important;
        transform: translateY(-1px);
    }}

    .stTabs [aria-selected="true"]:hover {{
        background-color: {NeutralColors.PRIMARY} !important;
        filter: brightness(0.9);
        border-color: {NeutralColors.PRIMARY} !important;
        box-shadow: 0 3px 10px rgba(33, 150, 243, 0.4) !important;
    }}

    .stTabs [data-baseweb="tab-panel"] {{
        padding-top: 0;
        background-color: transparent;
    }}

    .stTabs [data-baseweb="tab"]:focus {{
        outline: 2px solid {NeutralColors.PRIMARY};
        outline-offset: 2px;
        box-shadow: 0 0 0 4px rgba(33, 150, 243, 0.1);
    }}

    .stTabs [data-baseweb="tab"]:focus:not(:focus-visible) {{
        outline: none;
        box-shadow: 0 2px 6px rgba(0, 0, 0, 0.1);
    }}

    .tab-content {{
        padding: 1.5rem 0;
    }}

    /* Page padding paired with the negative-margin tab bleed above.
       Single source of truth: var(--block-pad) in :root. */
    .main > .block-container {{
        max-width: 100%;
        padding-left: var(--block-pad);
        padding-right: var(--block-pad);
    }}

    .stTabs [data-baseweb="tab"]:active {{
        transform: translateY(0);
        box-shadow: 0 1px 2px rgba(0, 0, 0, 0.1);
    }}

    .stTabs [data-baseweb="tab"][disabled] {{
        opacity: 0.5;
        cursor: not-allowed;
        transform: none;
    }}

    .stTabs [data-baseweb="tab"] > span {{
        display: flex;
        align-items: center;
        gap: 0.5rem;
    }}

    .stTabs [data-baseweb="tab"]::before {{
        content: '';
        position: absolute;
        top: 0;
        left: 0;
        right: 0;
        bottom: 0;
        border-radius: 8px;
        background: linear-gradient(180deg, rgba(255, 255, 255, 0.1) 0%, rgba(255, 255, 255, 0) 100%);
        pointer-events: none;
        opacity: 0;
        transition: opacity 0.2s ease;
    }}

    .stTabs [data-baseweb="tab"]:hover::before {{
        opacity: 1;
    }}

    .stTabs [aria-selected="true"]::before {{
        display: none;
    }}

    .stTabs [data-baseweb="tab"],
    .stTabs [data-baseweb="tab-list"] {{
        transition: background-color 0.3s ease, border-color 0.3s ease, color 0.3s ease;
    }}

    @media (max-width: 768px) {{
        /* Narrow the page padding token at mobile sizes; the tab strip
           and .main > .block-container both read --block-pad, so this
           one redefinition propagates to both. */
        :root {{
            --block-pad: 1rem;
        }}

        .stTabs [data-baseweb="tab-list"] {{
            padding-top: 0.75rem;
            padding-bottom: 0.75rem;
            overflow-x: auto;
            -webkit-overflow-scrolling: touch;
            scrollbar-width: thin;
            gap: 0.5rem;
            justify-content: flex-start;
        }}

        .stTabs [data-baseweb="tab"] {{
            padding: 0 1.25rem;
            font-size: 0.9rem;
            height: 44px;
            margin: 0 0.1875rem;
            flex: 0 0 auto;
            min-width: 120px;
        }}

        .stTabs [data-baseweb="tab-list"]::-webkit-scrollbar {{
            height: 4px;
        }}

        .stTabs [data-baseweb="tab-list"]::-webkit-scrollbar-track {{
            background: rgba(0, 0, 0, 0.05);
        }}

        .stTabs [data-baseweb="tab-list"]::-webkit-scrollbar-thumb {{
            background: rgba(0, 0, 0, 0.2);
            border-radius: 2px;
        }}
    }}
    </style>
    """


# ==================== COMPONENT STYLING FUNCTIONS ====================


def apply_custom_css():
    """Apply the unified theme CSS to the Streamlit app.

    Single global CSS injection — see ``get_neutral_css`` for the
    bundled rules. Called once per session from
    ``main.inject_custom_css``.
    """
    st.markdown(get_neutral_css(), unsafe_allow_html=True)


def create_info_box(
    content: str,
    type: str = "info",
    title: Optional[str] = None,
    icon: Optional[str] = None,
) -> str:
    """
    Create a themed info box styled for Streamlit with light/dark-friendly colors.

    Args:
        content (str): Main box content.
        type (str): One of 'info', 'success', 'warning', 'danger'.
        title (Optional[str]): Optional heading.
        icon (Optional[str]): Optional emoji or symbol.

    Returns:
        str: HTML snippet to render in Streamlit.
    """
    type_config = {
        "info": {
            "bg": theme.colors.info_bg,
            "border": theme.colors.info,
            "icon": "",
        },
        "success": {
            "bg": theme.colors.success_bg,
            "border": theme.colors.success,
            "icon": "",
        },
        "warning": {
            "bg": theme.colors.warning_bg,
            "border": theme.colors.warning,
            "icon": "⚠️",
        },
        "danger": {
            "bg": theme.colors.danger_bg,
            "border": theme.colors.danger,
            "icon": "❌",
        },
    }

    config = type_config.get(type, type_config["info"])
    icon = icon or config["icon"]

    # If there's a title, include icon with title
    if title:
        return f"""
        <div style='
            padding: 0.75rem 1rem;
            background-color: {config["bg"]};
            border-radius: 6px;
            border-left: 3px solid {config["border"]};
            margin-bottom: 0.75rem;
        '>
            <h4 style='
                color: currentColor;
                opacity: 0.9;
                margin: 0 0 0.25rem 0;
                font-size: 0.95rem;
                font-weight: 600;
                display: flex;
                align-items: center;
                gap: 0.5rem;
            '>
                <span style='font-size: 1rem;'>{icon}</span>
                {title}
            </h4>
            <p style='
                color: currentColor;
                opacity: 0.75;
                font-size: 0.85rem;
                margin: 0;
                line-height: 1.5;
            '>
                {content}
            </p>
        </div>
        """
    else:
        # No title, just icon with content
        return f"""
        <div style='
            padding: 0.75rem 1rem;
            background-color: {config["bg"]};
            border-radius: 6px;
            border-left: 3px solid {config["border"]};
            margin-bottom: 0.75rem;
        '>
            <p style='
                color: currentColor;
                opacity: 0.75;
                font-size: 0.85rem;
                margin: 0;
                line-height: 1.5;
                display: flex;
                align-items: flex-start;
                gap: 0.5rem;
            '>
                <span style='font-size: 1rem; line-height: 1.2;'>{icon}</span>
                <span>{content}</span>
            </p>
        </div>
        """


def style_dataframe(
    df, highlight_columns: Optional[list] = None, precision: int = 2
) -> str:
    """
    Apply styling to a pandas DataFrame for better display.

    Args:
        df: DataFrame to style
        highlight_columns: Columns to highlight (optional)
        precision: Decimal precision for floats

    Returns:
        Styled DataFrame
    """
    # Create styler
    styler = df.style

    # Set precision
    styler = styler.format(precision=precision)

    # Highlight specific columns if requested
    if highlight_columns:

        def highlight_cols(s):
            return [
                (
                    "background-color: var(--bg-hover)"
                    if s.name in highlight_columns
                    else ""
                )
                for _ in s
            ]

        styler = styler.apply(highlight_cols, axis=0)

    # Add hover effect
    styler = styler.set_table_styles(
        [
            {
                "selector": "tr:hover",
                "props": [("background-color", "var(--bg-hover)")],
            },
            {
                "selector": "th",
                "props": [
                    ("background-color", "var(--bg-hover)"),
                    ("color", "var(--text-primary)"),
                    ("font-weight", "600"),
                ],
            },
        ]
    )

    return styler


def create_styled_divider(style: str = "solid") -> str:
    """
    Create a styled divider.

    Args:
        style: Divider style (solid, gradient, dots)

    Returns:
        HTML string for the divider
    """
    if style == "gradient":
        return '<hr class="styled-divider">'
    elif style == "dots":
        return f"""
        <div style="
            text-align: center;
            margin: 32px 0;
            color: {NeutralColors.NEUTRAL_400};
            letter-spacing: 8px;
        ">•••</div>
        """
    else:
        return "<hr>"


# ==================== LAYOUT HELPERS ====================


def create_columns_with_gap(ratios: list, gap: str = "20px"):
    """
    Create columns with custom gap spacing.

    Args:
        ratios: List of column width ratios
        gap: Gap between columns

    Returns:
        List of column objects
    """
    # Apply custom CSS for gap
    st.markdown(
        f"""
    <style>
    .row-widget.stHorizontalBlock {{
        gap: {gap};
    }}
    </style>
    """,
        unsafe_allow_html=True,
    )

    return st.columns(ratios)


# ==================== THEME UTILITIES ====================


def get_chart_colors() -> list:
    """Get the chart color sequence for consistency."""
    return theme.colors.chart_colors  # Use unified theme colors


def apply_chart_theme(fig):
    """
    Apply neutral theme to Plotly charts.

    Args:
        fig: Plotly figure object

    Returns:
        Modified figure
    """
    fig.update_layout(
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        font=dict(
            family="-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
            color="var(--text-primary)",
        ),
        margin=dict(l=0, r=0, t=30, b=0),
        colorway=NeutralColors.CHART_COLORS,
        xaxis=dict(
            gridcolor="var(--border-color)",
            zerolinecolor="var(--border-color)",
        ),
        yaxis=dict(
            gridcolor="var(--border-color)",
            zerolinecolor="var(--border-color)",
        ),
    )
    return fig


# ==================== EXPORT ALL PUBLIC FUNCTIONS ====================

__all__ = [
    "NeutralColors",
    "apply_custom_css",
    "create_info_box",
    "style_dataframe",
    "create_styled_divider",
    "create_columns_with_gap",
    "get_chart_colors",
    "apply_chart_theme",
]
