# .streamlit/config.toml
# HMIS Data Analysis Suite — Professional Enterprise Theme

[theme]
# Valid Streamlit theme settings only
base = "light"
primaryColor = "#00629b"  # Deep professional blue
backgroundColor = "#FFFFFF"  # Clean white background  
secondaryBackgroundColor = "#F8FAFC"  # Subtle gray for contrast areas
textColor = "#1E293B"  # Dark slate for primary text

# ============ Application Settings ============
[client]
showSidebarNavigation = true
toolbarMode = "viewer"

[runner]
fastReruns = true
postScriptGC = true  # Better memory management

[server]
enableStaticServing = false
fileWatcherType = "poll"
enableWebsocketCompression = true
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 300  # MB
maxMessageSize = 200  # MB

[browser]
gatherUsageStats = false
serverAddress = "localhost"